name: wm01-dragon
dependencies:
  - python=3.11.7
  - pip=23.3.1
  - numpy=1.26.4
  - pandas=2.1.4
  - matplotlib=3.8.0
  - seaborn=0.12.2
  - scipy=1.11.4
  - scikit-image=0.22.0
  - scikit-learn=1.2.2
  - pytables=3.9.2
  - imageio=2.33.1
  - nbconvert=7.10.0
  - jupyter_server=2.10.0
  - requests=2.31.0
  - pytest=7.4.0
  - pip:
      - adskalman==0.3.11
      - ultralytics==8.1.9
