name: test

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4
      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
      - name: Run tests
        run: pytest
        shell: micromamba-shell {0}
        # No shell on windows. https://github.com/mamba-org/setup-micromamba/issues/32
        if: ${{ matrix.os != 'windows-latest' }}
